// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID     string `json:"id" bson:"_id"`
	Name   string `json:"name" bson:"name"`
	FaCode string `json:"fa_code" bson:"fa_code"`
	Color  string `json:"color" bson:"color"`
}

type EditTodo struct {
	ID         string      `json:"id" bson:"_id"`
	Name       *string     `json:"name" bson:"name"`
	CategoryID *string     `json:"category_id" bson:"category_id"`
	StartDate  *int        `json:"start_date" bson:"start_date"`
	Repeatable *bool       `json:"repeatable" bson:"repeatable"`
	Repeat     *EditRepeat `json:"repeat" bson:"repeat"`
}

type NewTodo struct {
	Name       string     `json:"name" bson:"name"`
	CategoryID string     `json:"category_id" bson:"category_id"`
	StartDate  int        `json:"start_date" bson:"start_date"`
	Repeatable bool       `json:"repeatable" bson:"repeatable"`
	Repeat     *NewRepeat `json:"repeat" bson:"repeat"`
}

type Repeat struct {
	Rule  string `json:"rule" bson:"rule"`
	Value []*int `json:"value" bson:"value"`
}

type Todo struct {
	ID         string    `json:"id" bson:"_id"`
	Name       string    `json:"name" bson:"name"`
	Category   *Category `json:"category" bson:"category"`
	Checked    []*int    `json:"checked" bson:"checked"`
	StartDate  int       `json:"start_date" bson:"start_date"`
	Repeatable bool      `json:"repeatable" bson:"repeatable"`
	Repeat     *Repeat   `json:"repeat" bson:"repeat"`
}

type EditRepeat struct {
	Rule  string `json:"rule" bson:"rule"`
	Value []*int `json:"value" bson:"value"`
}

type NewCategory struct {
	Name   string `json:"name" bson:"name"`
	FaCode string `json:"fa_code" bson:"fa_code"`
	Color  string `json:"color" bson:"color"`
}

type NewRepeat struct {
	Rule  string `json:"rule" bson:"rule"`
	Value []*int `json:"value" bson:"value"`
}

type ToggleCheck struct {
	TodoID string `json:"todo_id" bson:"todo_id"`
	Date   *int   `json:"date" bson:"date"`
}
